# Generated by Django 5.1.4 on 2026-09-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletters', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['company', 'status'], name='newsletters_company_7cf073_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['status', 'scheduled_at'], name='newsletters_status_930d15_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterrecipient',
            index=models.Index(fields=['newsletter', 'status'], name='newsletters_newslet_642289_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterrecipient',
            index=models.Index(fields=['tracking_token'], name='newsletters_trackin_6244fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsletterrecipient',
            unique_together={('newsletter', 'subscriber')},
        ),
    ]
