# Generated by Django 5.1.4 on 2026-09-16 14:39

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('home_address', models.TextField(blank=True)),
                ('is_subscribed', models.BooleanField(db_index=True, default=True)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'Spreadsheet Import'), ('website', 'Website Form'), ('enquiry', 'Enquiry Form'), ('registration', 'Registration'), ('api', 'API'), ('other', 'Other')], default='manual', max_length=30)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('marketing_consent', models.BooleanField(default=True)),
                ('sms_consent', models.BooleanField(default=False)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails_sent', models.PositiveIntegerField(default=0)),
                ('total_emails_opened', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscribers', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags for advanced filtering', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='subscribers_email_02be27_idx'), models.Index(fields=['company', 'is_subscribed'], name='subscribers_company_826d0f_idx'), models.Index(fields=['is_subscribed', 'is_active'], name='subscribers_is_subs_ad96c2_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
