# Generated by Django 5.1.4 on 2026-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='tags',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
