# Generated by Django 5.1.4 on 2026-09-16 14:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official company name', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Short display name', max_length=50)),
                ('is_parent', models.BooleanField(default=False, help_text='True only for REY Corporate Group')),
                ('logo', models.ImageField(blank=True, help_text='Main logo (transparent PNG preferred)', null=True, upload_to='logos/%Y/%m/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to='logos/%Y/%m/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('primary_color', models.CharField(default='#0A2540', help_text='Hex color e.g. #0A2540', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#C9A227', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(blank=True, default='#1E3A5F', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('domain', models.CharField(blank=True, help_text='e.g. sandstone.com.np', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('from_email', models.EmailField(help_text='Default sender for this company', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for REY Corporate Group (parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='companies.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_c_slug_45751b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_parent', 'is_active'], name='companies_c_is_pare_f74b35_idx'),
        ),
    ]
