# Generated by Django 5.1.4 on 2026-09-16 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('block_type', models.CharField(choices=[('header', 'Header with Logo'), ('hero', 'Hero Banner'), ('text', 'Rich Text'), ('image', 'Image'), ('button', 'CTA Button'), ('divider', 'Divider'), ('spacer', 'Spacer'), ('columns', 'Two Columns'), ('footer', 'Footer'), ('social', 'Social Links'), ('product', 'Featured Property / Product')], max_length=30)),
                ('html_snippet', models.TextField(help_text='HTML with {{ placeholders }}')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blocks/')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all companies')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='companies.company')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('type', models.CharField(choices=[('thank_you_enquiry', 'Thank You – Enquiry'), ('thank_you_registration', 'Thank You – Registration'), ('thank_you_event', 'Thank You – Event / Attendance'), ('invitation', 'Event Invitation'), ('newsletter_base', 'Newsletter Base Layout'), ('welcome', 'Welcome Series'), ('custom', 'Custom / Manual Send')], db_index=True, max_length=40)),
                ('subject', models.CharField(help_text='Supports {{ variables }}', max_length=300)),
                ('preheader', models.CharField(blank=True, max_length=200)),
                ('html_body', models.TextField(help_text='Full HTML. Use {{ full_name }}, {{ company.name }}, etc.')),
                ('plain_text', models.TextField(blank=True, help_text='Auto-generated if left blank')),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('header_bg', models.CharField(blank=True, max_length=7)),
                ('footer_bg', models.CharField(blank=True, max_length=7)),
                ('logo_settings', models.JSONField(blank=True, default=dict, help_text='{"width": 180, "height": 60, "align": "center", "crop": {...}}')),
                ('is_default', models.BooleanField(default=False, help_text='Default for this type + company')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='templates_app.emailtemplate')),
            ],
            options={
                'ordering': ['company', 'type', '-is_default', 'name'],
                'indexes': [models.Index(fields=['company', 'type', 'is_default'], name='templates_a_company_9b9886_idx')],
                'unique_together': {('company', 'slug')},
            },
        ),
    ]
