# Generated by Django 5.1.4 on 2026-09-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='subscribers.subscriber'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['company', 'status'], name='enquiries_e_company_0a9df0_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['email'], name='enquiries_e_email_45d08c_idx'),
        ),
    ]
